#include <e32base.h>

#include "htmlstrings.h"

#define ___LIT(name,s) const TLitC16<sizeof(L##s)/2> name={sizeof(L##s)/2-1,L##s}

___LIT(KHStrTrue, "true");
___LIT(KHStrFalse, "false");
___LIT(KHStrEnabled, "enabled");
___LIT(KHStrChecked, "checked");
___LIT(KHStrDisabled, "disabled");
___LIT(KHStrBlack, "black");
___LIT(KHStrRed, "red");
___LIT(KHStrGreen, "green");
___LIT(KHStrBlue, "blue");
___LIT(KHStrYellow, "yellow");
___LIT(KHStrMagenta, "magenta");
___LIT(KHStrCyan, "cyan");
___LIT(KHStrGray, "gray");
___LIT(KHStrWhite, "white");
___LIT(KHStrTransparent, "transparent");
___LIT(KHStrXXSmall, "xx-small");
___LIT(KHStrXSmall, "x-small");
___LIT(KHStrSmall, "small");
___LIT(KHStrMedium, "medium");
___LIT(KHStrLarge, "large");
___LIT(KHStrXLarge, "x-large");
___LIT(KHStrXXLarge, "xx-large"); 
___LIT(KHStrAlign,"align");
___LIT(KHStrLeft, "left");
___LIT(KHStrRight, "right");
___LIT(KHStrCenter, "center");
___LIT(KHStrTop, "top");
___LIT(KHStrMiddle, "middle");
___LIT(KHStrBottom, "bottom");
___LIT(KHStrBoth, "both");
___LIT(KHStrPosition,"position");
___LIT(KHStrRelative,"relative");
___LIT(KHStrAbsolute,"absolute");
___LIT(KHStrNone, "none");
___LIT(KHStrDotted, "dotted");
___LIT(KHStrDashed, "dashed");
___LIT(KHStrOutset, "outset");
___LIT(KHStrInset, "inset");
___LIT(KHStrAuto, "auto");
___LIT(KHStrVisible, "visible");
___LIT(KHStrHidden, "hidden");
___LIT(KHStrScroll, "scroll");
___LIT(KHStrDisplay, "display");
___LIT(KHStrBlock, "block");
___LIT(KHStrAnnotation, "annotation");
___LIT(KHStrTitle, "title");
___LIT(KHStrLegend, "legend");
___LIT(KHStrSymbol, "symbol");
___LIT(KHStrDense, "dense");
___LIT(KHStrItalic, "italic");
___LIT(KHStrOblique, "oblique");
___LIT(KHStrBold, "bold");
___LIT(KHStrUnderline, "underline");
___LIT(KHStrLineThrough, "line-through");
___LIT(KHStrColor, "color");
___LIT(KHStrFontSize, "font-size");
___LIT(KHStrFontStyle, "font-style");
___LIT(KHStrFontWeight, "font-weight");
___LIT(KHStrTextDecoration, "text-decoration");
___LIT(KHStrFontFamily, "font-family");
___LIT(KHStrLineHeight, "line-height");
___LIT(KHStrTextAlign, "text-align");
___LIT(KHStrLineVAlign, "line-valign");
___LIT(KHStrBackgroundColor, "background-color");
___LIT(KHStrBackgroundImage,  "background-image");
___LIT(KHStrBackgroundPosition,  "background-position");
___LIT(KHStrBackgroundRepeat,  "background-repeat");
___LIT(KHStrBackgroundPattern,  "background-pattern");
___LIT(KHStrSolid,"solid");
___LIT(KHStrVerticalHatch,"vertical-hatch");
___LIT(KHStrForwardDiagonalHatch,"forward-diagnoal-hatch");
___LIT(KHStrHorizontalHatch,"horizontal-hatch");
___LIT(KHStrRearwardDiagonalHatch,"rearward-diagnoal-hatch");
___LIT(KHStrSquareCrossHatch,"square-cross-hatch");
___LIT(KHStrDiamondCrossHatch,"diamond-cross-hatch");
___LIT(KHStrRepeat,  "repeat");
___LIT(KHStrNoRepeat,  "no-repeat");
___LIT(KHStrRepeatX,  "repeat-x");
___LIT(KHStrRepeatY,  "repeat-y");
___LIT(KHStrStretch,  "stretch");
___LIT(KHStrBorder, "border");
___LIT(KHStrBorderWidth, "border-width");
___LIT(KHStrBorderColor, "border-color");
___LIT(KHStrBorderLeft, "border-left");
___LIT(KHStrBorderRight, "border-right");
___LIT(KHStrBorderTop, "border-top");
___LIT(KHStrBorderBottom, "border-bottom");
___LIT(KHStrWidth, "width");
___LIT(KHStrHeight, "height");
___LIT(KHStrMaxWidth, "max-width");
___LIT(KHStrMargin, "margin");
___LIT(KHStrMarginTop, "margin-top");
___LIT(KHStrMarginBottom, "margin-bottom");
___LIT(KHStrMarginLeft, "margin-left");
___LIT(KHStrMarginRight, "margin-right");
___LIT(KHStrPadding, "padding");
___LIT(KHStrPaddingTop, "padding-top");
___LIT(KHStrPaddingBottom, "padding-bottom");
___LIT(KHStrPaddingLeft, "padding-left");
___LIT(KHStrPaddingRight, "padding-right");
___LIT(KHStrClear, "clear");
___LIT(KHStrFilter, "filter");
___LIT(KHStrOverflow, "overflow");
___LIT(KHStrVisibility, "visibility");
___LIT(KHStrLineWrap, "line-wrap");
___LIT(KHStrClip, "clip");
___LIT(KHStrAlt, "alt");
___LIT(KHStrRemark, "remark");
___LIT(KHStrError, "error");
___LIT(KHStrId, "id");
___LIT(KHStrName, "name");
___LIT(KHStrFocusing, "focusing");
___LIT(KHStrSize, "size");
___LIT(KHStrStyle, "style");
___LIT(KHStrRes, "res");
___LIT(KHStrInnerText, "innertext");
___LIT(KHStrInnerHtml, "innerhtml");
___LIT(KHStrClass, "class");
___LIT(KHStrFocusClass, "focus-class");
___LIT(KHStrFocusStyle, "focus-style");
___LIT(KHStrDownClass, "down-class");
___LIT(KHStrDownStyle, "down-style");
___LIT(KHStrScrollLoop, "scroll-loop");
___LIT(KHStrScrollStep, "scroll-step");
___LIT(KHStrScrollPos, "scroll-pos");
___LIT(KHStrScrollMax, "scroll-max");
___LIT(KHStrScrollVisible, "scroll-visible");
___LIT(KHStrScrollOnSlide, "scroll-on-slide");
___LIT(KHStrSrc, "src");
___LIT(KHStrFocusSrc, "focus-src");
___LIT(KHStrFullPath, "fullpath");
___LIT(KHStrAnimation, "animation");
___LIT(KHStrValue, "value");
___LIT(KHStrMaxLength, "max-length");
___LIT(KHStrBufSize, "buf-size");
___LIT(KHStrType, "type");
___LIT(KHStrText, "text");
___LIT(KHStrCheckbox, "checkbox");
___LIT(KHStrPassword, "password");
___LIT(KHStrRadio, "radio");
___LIT(KHStrButton, "button");
___LIT(KHStrSubmit, "submit");
___LIT(KHStrFile, "file");
___LIT(KHStrImage, "image");
___LIT(KHStrRows, "rows");
___LIT(KHStrInputMode, "input-mode");
___LIT(KHStrReadOnly, "readonly");
___LIT(KHStrNumber, "number");
___LIT(KHStrAll, "all");
___LIT(KHStrAlpha, "alpha");
___LIT(KHStrSelected, "selected");
___LIT(KHStrSelectedIndex, "selected-index");
___LIT(KHStrTextArray, "text-array");
___LIT(KHStrValueArray, "value-array");
___LIT(KHStrOptionArray, "option-array");
___LIT(KHStrDrawLines, "draw-lines");
___LIT(KHStrLineColor, "line-color");
___LIT(KHStrHref, "href");
___LIT(KHStrBody, "body");
___LIT(KHStrHead,"head");
___LIT(KHStrScript,"script");
___LIT(KHStrB,"b");
___LIT(KHStrStrong,"strong");
___LIT(KHStrI,"i");
___LIT(KHStrU,"u");
___LIT(KHStrFont,"font");
___LIT(KHStrP,"p");
___LIT(KHStrBr, "br");
___LIT(KHStrHr, "hr");
___LIT(KHStrBlockQuote,"blockquote");
___LIT(KHStrLi,"li");
___LIT(KHStrTr,"tr");
___LIT(KHStrTable,"table");
___LIT(KHStrTd,"td");
___LIT(KHStrOption,"option");
___LIT(KHStrParam,"param");
___LIT(KHStrA, "a");
___LIT(KHStrTarget, "target");
___LIT(KHStrImg, "img");
___LIT(KHStrDiv, "div");
___LIT(KHStrSpan, "span");
___LIT(KHStrForm, "form");
___LIT(KHStrMethod, "method");
___LIT(KHStrAction, "action");
___LIT(KHStrEncType, "enctype");
___LIT(KHStrFormData, "form-data");
___LIT(KHStrInput, "input");
___LIT(KHStrSelect, "select");
___LIT(KHStrClassId, "classid");
___LIT(KHStrData, "data");
___LIT(KHStrEmbed, "embed");
___LIT(KHStrObject, "object");
___LIT(KHStrTextArea, "textarea");
___LIT(KHStrStyleDot, "style.");
___LIT(KHStrListItemCount, "list-item-count");
___LIT(KHStrListSelectedIndex, "list-selected-index");
___LIT(KHStrListTopIndex, "list-top-index");
___LIT(KHStrListItemHtml, "list-item-html");
___LIT(KHStrListEmptyHtml, "list-empty-html");
___LIT(KHStrSelector, "selector");
___LIT(KHStrLink, "link");
___LIT(KHStrHover, "hover");
___LIT(KHStrFocus, "focus");
___LIT(KHStrDown, "down");
___LIT(KHStrTabStop, "tabstop");
___LIT(KHStrDirectFocus, "direct-focus");
___LIT(KHStrSub, "sub");
___LIT(KHStrSup, "sup");
___LIT(KHStrAccessKey, "accesskey");

___LIT(KHStrCreateSlides, "create-slides");
___LIT(KHStrCreateList, "create-list");
___LIT(KHStrCreateGrid, "create-grid");
___LIT(KHStrAddOption, "add-option");
___LIT(KHStrRemoveOption, "remove-option");
___LIT(KHStrClearOptions, "clear-options");
___LIT(KHStrUpdate, "update");
___LIT(KHStrUpdateAll, "update-all");
___LIT(KHStrClick, "click");
